### ISSUE TITLE
`env.isDevelopment()` does not work inside React

### ISSUE THREAD

**Issue by eordano** [decentraland/commons#6]
We should add a function like `isBrowser()` -- so that we can check `REACT_APP_NODE_ENV` so we know where to look for when checking if we are in dev or prod

**Comment by NicoSantangelo** [comment]
There's already a `process.browser` prop injected by webpack! we're using it here: https://github.com/decentraland/commons/blob/master/src/env.js to avoid trying to use dotenv to read env variables from a file on the browser.

The thing is, NODE_ENV is supported by `create react app`, from [the docs](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables):

> There is also a special built-in environment variable called NODE_ENV. You can read it from process.env.NODE_ENV. When you run npm start, it is always equal to 'development', when you run npm test it is always equal to 'test', and when you run npm run build to make a production bundle, it is always equal to 'production'. You cannot override NODE_ENV manually. This prevents developers from accidentally deploying a slow development build to production.

So it should be working!
If the problem is that we're running a production build for a beta version, we can use another env varible, like `REACT_APP_ENVIRONMENT=['live', 'test', etc...]`. I wouldn't name it `REACT_APP_NODE_ENV` to avoid confusion with the existing `NODE_ENV`

**Comment by eordano** [comment]
Thanks. Must be user error then.
